name: Run Cypress Tests with Docker

on:
  push:
    branches:
      - e2e

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:latest
      volumes:
        - ${{ github.workspace }}/cypress.config.js:/e2e/cypress.config.js
        - ${{ github.workspace }}/cypress:/e2e/cypress
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
