name: Deploy to FTP Server

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y lftp

    - name: Deploy to FTP server
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_REMOTE_PATH: ${{ secrets.FTP_REMOTE_PATH }}
      run: |
        lftp -e "set ftp:ssl-allow no; mirror --reverse --only-newer --delete --verbose --exclude-glob-from=.lftpignore ./ $FTP_REMOTE_PATH; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
